"""
schemas.py - All Pydantic data models for the HTP Assessment Service.

Two-layer output design:
  - Dashboard JSON (AssessmentResponse) → structured data for the psychologist UI
  - PDF Report → detailed clinical document generated by the pipeline
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from enum import Enum


# ─────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────

class Gender(str, Enum):
    male            = "male"
    female          = "female"
    other           = "other"
    prefer_not_say  = "prefer_not_to_say"


class ReferralSource(str, Enum):
    self_referred   = "self_referred"
    doctor          = "doctor"
    family          = "family"
    school          = "school"
    court           = "court"
    other           = "other"


class Severity(str, Enum):
    low      = "low"
    moderate = "moderate"
    high     = "high"


class DrawingConsistency(str, Enum):
    consistent    = "consistent"
    contradictory = "contradictory"
    neutral       = "neutral"


# ─────────────────────────────────────────────
# Patient Inputs
# ─────────────────────────────────────────────

class DASS21Scores(BaseModel):
    """
    Subscale scores from DASS-21.
    Each subscale raw score is 0-21 (multiply item sum × 2 for severity mapping).
    """
    depression : Optional[int] = Field(None, ge=0, le=42, description="DASS-21 Depression subscale score")
    anxiety    : Optional[int] = Field(None, ge=0, le=42, description="DASS-21 Anxiety subscale score")
    stress     : Optional[int] = Field(None, ge=0, le=42, description="DASS-21 Stress subscale score")


class AssessmentRequest(BaseModel):
    """
    Request payload to start an assessment via the background worker queue.
    """
    assessment_id: str = Field(..., description="The unique UUID of the assessment in the Supabase database.")


class PatientContext(BaseModel):
    """
    All patient information collected BEFORE the HTP drawing session.

    The platform (Next.js) should collect and POST these fields from:
      - Registration / onboarding form (age, gender)
      - Pre-session questionnaire module (phq9_score, dass21)
      - Session intake form (presenting_complaint, relevant_history, referral_source)

    PRIVACY NOTE:
      - patient_id is for audit logging only; it is NEVER included in the
        body of the clinical report (Rule 7).
      - Do NOT send full name — use patient_id only.
    """
    patient_id            : str   = Field(..., description="Platform UUID for this patient — used for audit log only")
    age                   : int   = Field(..., ge=5,  le=100, description="Patient age in years")
    gender                : Gender
    presenting_complaint  : str   = Field(..., min_length=10,
                                          description="Main reason for seeking help, in patient's own words")
    relevant_history      : Optional[str] = Field(
        None,
        description=(
            "Brief relevant background: family situation, trauma, medication, "
            "previous diagnoses (if any). Keep factual and concise."
        )
    )
    referral_source       : Optional[ReferralSource] = None

    # Scores already collected by the platform's questionnaire module
    phq9_score            : Optional[int]        = Field(None, ge=0, le=27,
                                                          description="PHQ-9 total score (0-27)")
    dass21                : Optional[DASS21Scores] = None


# ─────────────────────────────────────────────
# Phase 1 — Drawing Feature Extraction
# ─────────────────────────────────────────────

class DrawingFeatures(BaseModel):
    """
    Structured visual features extracted by Gemini Flash from a single drawing.
    Gemini returns this directly as JSON via response_schema — no manual parsing needed.
    """
    drawing_type    : str          # "House" | "Tree" | "Person"
    line_quality    : str          # e.g. "Heavy and consistent throughout"
    size            : str          # "Small", "Average", "Large" relative to page
    placement       : str          # e.g. "Centered, slightly left of midline"
    omissions       : List[str]    # e.g. ["No roots visible", "Missing chimney"]
    shading_areas   : List[str]    # e.g. ["Heavy shading on torso", "Shaded windows"]
    distortions     : str          # e.g. "Door disproportionately small relative to house"
    key_details     : List[str]    # Any other clinically notable features
    confidence_score: float        # 0.0 – 1.0: how clearly the drawing could be analyzed
    clinical_flags  : List[str]    # Features that warrant urgent psychologist attention


# ─────────────────────────────────────────────
# Dashboard JSON — Structured for frontend UI
# ─────────────────────────────────────────────

class Observation(BaseModel):
    """A single feature → interpretation pair for a drawing."""
    feature        : str   # "Locked door with no handle"
    interpretation : str   # "May suggest defensiveness or reluctance to allow others in"


class DrawingSummary(BaseModel):
    """Per-drawing summary card for the dashboard."""
    drawing_type   : str
    confidence     : float
    observations   : List[Observation]   # Variable count


class ThemeItem(BaseModel):
    """A cross-drawing psychological theme with severity."""
    theme    : str   # "Emotional Guardedness"
    evidence : str   # "Locked door on house, arms close to body, absence of leaves"
    severity : str   # "low" | "moderate" | "high"


class QuestionnaireScore(BaseModel):
    """Score + severity + correlation with drawing features."""
    score               : int
    severity            : str        # "Minimal" | "Mild" | "Moderate" | etc.
    drawing_consistency : str        # "consistent" | "contradictory" | "neutral"


class QuestionnaireSummary(BaseModel):
    """Questionnaire correlation data for the dashboard."""
    phq9             : Optional[QuestionnaireScore] = None
    dass21_depression: Optional[QuestionnaireScore] = None
    dass21_anxiety   : Optional[QuestionnaireScore] = None
    dass21_stress    : Optional[QuestionnaireScore] = None


class ReportSummary(BaseModel):
    """Top-level summary for the dashboard header."""
    clinical_impression : str             # One clear paragraph
    key_themes          : List[ThemeItem]  # Cross-drawing themes with severity
    risk_flags          : List[str]        # Urgent flags (red alerts)


class AssessmentResponse(BaseModel):
    """
    Full structured response for the psychologist dashboard.

    This JSON is stored in the `ai_report_json` column in Supabase.
    The detailed clinical PDF is stored separately at `pdf_report_url`.
    """
    patient_id              : str
    assessed_at             : str
    overall_confidence      : float
    summary                 : ReportSummary
    drawings                : List[DrawingSummary]
    questionnaire_match     : Optional[QuestionnaireSummary] = None
    session_focus_areas     : List[str]
    pdf_report_url          : Optional[str] = None
    processing_time_seconds : float
    disclaimer              : str


class ErrorResponse(BaseModel):
    error   : str
    detail  : Optional[str] = None
